######################################################################
# Automatically generated by qmake (2.01a) Sun Aug 15 17:09:01 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += summator.h \
    summatorform.h
SOURCES += main.cpp summator.cpp \
    summatorform.cpp
