# #####################################################################
# Automatically generated by qmake (2.01a) Fri Nov 27 19:13:45 2009
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    dialog.cpp
HEADERS += dialog.h \
    CustomItemDelegate.h
