# #####################################################################
# Automatically generated by qmake (2.01a) Fri Nov 27 20:07:26 2009
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
				listmodel.cpp

HEADERS += listmodel.h\
				ListView.h
