######################################################################
# Automatically generated by qmake (2.01a) Sun Jan 24 19:12:03 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
HEADERS += Test.h
