######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 10 10:45:35 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += createModel.h
SOURCES += main.cpp
