######################################################################
# Automatically generated by qmake (2.01a) Sun Feb 7 15:45:12 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
